<a href="https://colab.research.google.com/github/Anushree-B/assignments/blob/main/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1

Q1. Maximum elements from matrix

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
max=np.amax(mat)
print("Maximum element is: ",max)

Maximum element is:  7


Q2. Get the minimum value from given matrix

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
min=np.amin(mat)
print("Minimum element is: ",min)

Minimum element is:  1


Q3.  Find the number of rows and columns of a given matrix using NumPy

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
arr=np.shape(mat)
print("The number of rows is : ",arr[0])
print("The number of coulumns is : ",arr[1])

The number of rows is :  4
The number of coulumns is :  3


Q4. Select the elements from a given matrix

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
print("The elements in 1st 2 row are: \n",mat[0:2])
print("The elements selected are")
select_elements=[mat[1,2],mat[2,1],mat[3,0]]
print(select_elements)

The elements in 1st 2 row are: 
 [[2 4 6]
 [1 2 3]]
The elements selected are
[3, 5, 6]


Q5.Find the sum of values in a matrix

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
print("The sum of elements in matrix is: ",np.sum(mat))

The sum of elements in matrix is:  47


Q6. Perform addition and subtraction of two matrices

In [ ]:
import numpy as np
mat1=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
mat2=np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
print("The addition of mat 1 and mat 2 is: \n",np.add(mat1,mat2))
print("The subtraction of mat 1 and mat 2 is: \n",np.subtract(mat1,mat2))

The addition of mat 1 and mat 2 is: 
 [[ 3  5  7]
 [ 3  4  5]
 [ 7  8  6]
 [10 11  8]]
The subtraction of mat 1 and mat 2 is: 
 [[ 1  3  5]
 [-1  0  1]
 [ 1  2  0]
 [ 2  3  0]]


Q7. Matrix Multiplication in NumPy

In [ ]:
import numpy as np
mat1=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
mat2=np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
print("The multiplication of mat 1 and mat 2 is: \n",np.multiply(mat1,mat2))

The multiplication of mat 1 and mat 2 is: 
 [[ 2  4  6]
 [ 2  4  6]
 [12 15  9]
 [24 28 16]]


Q8. How to count the frequency of unique values in NumPy array?

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
unique, frequency = np.unique(mat, return_counts = True)
print("unique: ",unique)
print("frequency ",frequency)

unique:  [1 2 3 4 5 6 7]
frequency  [1 2 2 3 1 2 1]


Q9. Convert the matrix into a list

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
list1=[]

for x in np.array(mat).flat:
    list1.append(x)

print(list1)

[2, 4, 6, 1, 2, 3, 4, 5, 3, 6, 7, 4]


Q10. Replace negative value with zero in numpy array

In [ ]:
import numpy as np
mat=np.array([[2,-4,6],[-1,2,3],[-4,5,-3],[6,-7,4]])
mat[mat<0]=0
print(mat)

[[2 0 6]
 [0 2 3]
 [0 5 0]
 [6 0 4]]


Q11.Compute the median of the flattened NumPy array

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
mat=np.array(mat).flat
print("Median :",np.median(mat))

Median : 4.0


Q12.Find Mean of a List of Numpy Array

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
list1=[]

for x in np.array(mat).flat:
    list1.append(x)
print("Mean :",np.mean(list1))

Mean : 3.9166666666666665


Q13.Get the mean value from given matrix

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
print("Mean :",np.mean(mat))

Mean : 3.9166666666666665


Q14.Compute the variance of the NumPy array

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
print("Variance: ",np.var(mat))

Variance:  3.076388888888889


Q15.Compute the standard deviation of the NumPy array

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
print("Standard deviation: ",np.std(mat))

Standard deviation:  1.7539637649874324


Q16.Create a 5X2 integer array from a range between 100 to 200 such that the  difference between each element is 10

In [ ]:
import numpy as np
list=[]
for i in range(100,200,10):
    list.append(i)
print(list)
arr=np.array(list)
print(arr)
arr.reshape(5,2)

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
[100 110 120 130 140 150 160 170 180 190]


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Q17.Following is the provided numPy array. Return array of items by taking  the third column from all rows

In [ ]:
import numpy as np
mat=np.array([[2,4,6],[1,2,3],[4,5,3],[6,7,4]])
third_col=[]
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
for i in range(len(sampleArray)):
    third_col.append(sampleArray[i,2])
print(third_col)

[33, 66, 99]
